### ISSUE TITLE
CJT parameters shortcode error: Could not find block specified! 

### ISSUE THREAD

**Issue by wipeoutmedia** [wipeoutmedia/css-javascript-toolbox#12]
Hi Ivan,

Sorry for the long ticket. 
I will post user emails that relate to this issue as it is a fairly uncommon and elusive occurrence. I believe all of these email are related. 
I am not that sure why it happens, but from memory, I think it may happen due to these scenarios:
- before or after the very first code block is created  (strange elusive bug) 
- a misspelled code block title used as a shortcode
- a non-existent code block title is used as a shortcode

Either way, it really should be managed better I think.  It would be great to solve this one.  

Also, I have emailed Jeff (just below) for more information and screenshots so we can understand exactly how he got that error.  

Regards,
Damian
_______________________________________________

Name
 	Jeff Aberle
Email
 	docaberle@charter.net
Website
 	http://www.aberlechiropractic.com
Message
 	Hello,
I'm using the free version of your plugin and when I use the shortcode in my page, the tags get stripped off and some tags get added occasionally. I've searched high and low for a way to turn this "feature" off. Do you have that option in your Pro version or something? Or is there a way to turn these filters off like with your shortcode:
Could not find block specified! Please check out the Shortcode parameters. or [raw]Could not find block specified! Please check out the Shortcode parameters.[/raw]

This would be so cool. I seem to be getting away with not using the shortcode at all and just applying my code using the "Pages" checkbox section of your plugin, but then I can't include anything in a direct page using the WYSIWYG editor.

Happy to buy the pro version if it has this feature. There are some [raw] [/raw] shortcodes out there, but they're old plugins that are not kept up to date.
Thanks,
Jeff

User Information

Name: Jeff Aberle
Date: 02/03/2016
Entry ID: 339

IP Address: 24.178.22.58
Entry URL: http://css-javascript-toolbox.com/wp-admin/admin.php?page=gf_entries&view=entry&id=1&lid=339
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

_______________________________________________

Name
 	Marcel Trapman
Email
 	marceltrapman@it2be.com
Message
 	Hi,

Apologies for my 3rd email but I have found 'functions.php' which helps me with a couple of issues I had :)

So now I can be much more specific with what I want/need:

1. It does not matter if I create a codeblock on a page or global, the output is always echo'd to the header as well as to the position that I inserted the block. 

That is not what I want/need. It really has to be only at the position where I insert the block. Can you please tell me how to do this?
I have a screenshot what it currently looks like if you want it.

2. What I would like to do, ideally, is re-use a code block. So instead of redefining code I would like to be able to use a variable.
I think it could look like: Could not find block specified! Please check out the Shortcode parameters.. I am not sure if this is even possible...
Thanks,
Marcel

User Information
Name: Marcel Trapman
Date: 23/11/2015
Entry ID: 297

IP Address: 93.237.253.103
Entry URL: http://css-javascript-toolbox.com/wp-admin/admin.php?page=gf_entries&view=entry&id=1&lid=297
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7

_______________________________________________

Name
 	Brian
Email
 	glasner1982@gmail.com
Website
 	http://applianceplusoutlet.com
Message
 	Hey there! I just wanted to say I really like your plugin! For the longest time I was fighing with Wordpress changing my javascript and html code when I would switch back and forth between visual and text mode on the edit page screen. So aggrivating since it kept breaking my code and it would no longer work! So I installed your plugin today and created my javascript and html codes in seperate templates and embeded those templates into individual code blocks, inserted the shortcode on my required page and BOOM!! It works perfectly!! I can switch back and forth from visual and text and it still works! So thank you for making this plugin!

One thing I want to mention. I am using Wordpress 4.0 so I don't know if this is the case with other versions but I think I may have found a bug. When I click on the little button to add the short code to my page it adds it as Could not find block specified! Please check out the Shortcode parameters. and it didn't work. It just displayed my code. So I poked around this site and found the section where you explain using short codes and you have it on your website as Could not find block specified! Please check out the Shortcode parameters. (with double quotes instead of single quotes). So I went back to my edit page and changed the single quotes to double quotes and it works perfectly!

So I think there is a bug that is generating single quotes instead of double quotes. Even if I click on the info button on a code block it still says the short code with single quotes. Like I said before I am using Wordpress 4.0 so I don't know if this is the case with earlier versions. Something you may want to look into. Other than that it's perfect!
Best wishes
Brian

User Information
Name: Brian
Date: 07/11/2014
Entry ID: 202

IP Address: 72.88.20.141
Entry URL: http://css-javascript-toolbox.com/wp-admin/admin.php?page=gf_entries&view=entry&id=1&lid=202
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

_______________________________________________

Name
 	Nathan
Email
 	nathan@somethingdifferent.com
Message
 	is there a way to pass a variable from the shortcode to the script.

For example... 
Could not find block specified! Please check out the Shortcode parameters.
I would like to add a few varibles.
Could not find block specified! Please check out the Shortcode parameters.
the code would catch the variable "title" or "height" and use it in the php code. It would allow me to use the code spinet in many more ways (sorta like a class). I would catch the value of the variable in the code.

User Information
Name: Nathan
Date: 20/02/2014
Entry ID: 123

IP Address: 173.10.9.229
Entry URL: http://css-javascript-toolbox.com/wp-admin/admin.php?page=gf_entries&view=entry&id=1&lid=123
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0

**Comment by ivanwebpro** [comment]
As we discussed before, first issue (Jeff) isn't related to shortcode parameters at all.

Second issue (Marcel) I splitted to https://github.com/wipeoutmedia/css-javascript-toolbox/issues/30 and https://github.com/wipeoutmedia/css-javascript-toolbox-plus/issues/66

Third issue (Brian) seems to be related to using quotes in block name and it isn't bug at all (name validation will be reviewed in https://github.com/wipeoutmedia/css-javascript-toolbox/issues/20 .

Fourth issue (Nathan) related to https://github.com/wipeoutmedia/css-javascript-toolbox-plus/issues/66 (as Marcel).

So this issue can be closed.
