### ISSUE TITLE
Database errors in logs

### ISSUE THREAD

**Issue by wipeoutmedia** [wipeoutmedia/css-javascript-toolbox#2]
This seems to be a frequent issue and I think it is time to resolve or at least manage these errors and warnings once and for all.  There are a number of users reporting this, which goes something like this:

On 23 Feb 2016, at 6:15 am, Justin Armstrong <quimbly@gmail.com> wrote:

Here is a typical error I'm getting:

[11-Feb-2016 20:01:22 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) ) ) )' at line 5 for query SELECT blocks.id, blocks.owner, blocks.name, blocks.pinPoint, blocks.location, blocks.links, blocks.expressions, (blocks.pinPoint & 81) blocksGroup

FROM wp_cjtoolbox_blocks blocks LEFT JOIN wp_cjtoolbox_block_pins pins ON blocks.id = pins.blockId

WHERE ( ( ( backupId IS NULL ) AND ( state = 'active' ) ) AND ( ( blocks.pinPoint & 81 ) OR ( ( blocks.pinPoint & 32 ) AND ( pins.pin = 'pages' ) AND ( pins.value IN ( ) ) ) ) ); made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), call_user_func_array, CJTBlocksCouplingController->initCoupling, CJTBlocksCouplingController->getBlocks, CJTCouplingModel->getPinsBlocks, CJTPinsBlockSQLView->exec, CJTMYSQLQueueDriver->select

I'm getting a LOT of these. Can you tell me what's going on?
Regards,
Justin

_____________________________________________

Here is another one:

On 25 Jan 2016, at 10:16 pm, Jesse Perry <jesse@teamflower.org> wrote:

Name
 	Jesse Perry
Email
 	jesse@teamflower.org
Message
 	So I recently turned on Wordpress logs to see if anything was amiss in my Wordpress. Everything is looking good.

However I noticed that every day around 2-3am EST, I get a "Wordpress database error" and it mentions this toolbox plugin. I have Toolbox Plus (and love it). Is this just some routine maintenance the plugin is doing at 2-3am and I should ignore it? The plugin (and I use the plugin on every page/post in my Wordpress) works fine and I haven't seen any issues.

See below on the details of the error:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') LEFT JOIN `wp_cjtoolbox_plus_block_pintype` pt ON blocks.`id` = pt.`blockId` W' at line 1 for query SELECT blocks.id,blocks.owner,blocks.name,blocks.pinPoint,blocks.location,blocks.links,blocks.expressions,0 as blocksGroup FROM wp_cjtoolbox_blocks blocks LEFT JOIN wp_cjtoolbox_block_pins pins0 ON blocks.id = pins0.blockId AND pins0.pin='categories' AND pins0.value IN( ) LEFT JOIN `wp_cjtoolbox_plus_block_pintype` pt ON blocks.`id` = pt.`blockId` WHERE ( ( ( `backupId` IS NULL ) AND ( `state` = "active" ) ) AND ( ( pt.pinName = 'category' AND pt.invert = 1 ) ) AND ( ( ( pins0.pin IS NULL ) AND ( pins0.value IS NULL ) ) ) ); made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), call_user_func_array, CJTBlocksCouplingController->initCoupling, CJTBlocksCouplingController->getBlocks, CJTCouplingModel->getPinsBlocks, apply_filters('cjt-blocks-coupling-model-blocks-queue'), call_user_func_array, CJTPlusHooksCJTBlockAssignmentNegative->_blocksQueue

User Information
Name: Jesse Perry
Date: 25/01/2016
Entry ID: 329

IP Address: 68.119.220.223
Entry URL: http://css-javascript-toolbox.com/wp-admin/admin.php?page=gf_entries&view=entry&id=1&lid=329
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9

_______________________________________

And here are some links to similar related issues:

https://wordpress.org/support/topic/all-kinds-of-database-errors
http://css-javascript-toolbox.com/support/topic/several-sites-where-cjt-will-not-load-or-is-showing-errors-in-the-log/
https://wordpress.org/support/topic/fatal-error-on-install-24
_______________________________________

I realise that some of these issues could be user-related as in they have PHP errors in their code within the code blocks.  However, I also believe that there are CJT related errors too.

Are we able to handle and manage these errors a lot better?
Such as:

Review errors handling / logging. For example, when I have installed your plugin on hosting with PHP 5.2 I have many error messages. It can make users very angry. Better to check PHP version before install and notice user about requirements ("ask support of your hosting to update PHP")
https://wordpress.org/support/topic/warning-and-fatal-error-12

**Comment by ivanwebpro** [comment]
> [11-Feb-2016 20:01:22 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) ) ) )' at line 5 for query SELECT blocks.id, blocks.owner, blocks.name, blocks.pinPoint, blocks.location, blocks.links, blocks.expressions, (blocks.pinPoint & 81) blocksGroup
> 
> FROM wp_cjtoolbox_blocks blocks LEFT JOIN wp_cjtoolbox_block_pins pins ON blocks.id = pins.blockId
> 
> WHERE ( ( ( backupId IS NULL ) AND ( state = 'active' ) ) AND ( ( blocks.pinPoint & 81 ) OR ( ( blocks.pinPoint & 32 ) AND ( pins.pin = 'pages' ) AND ( pins.value IN ( ) ) ) ) ); made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), call_user_func_array, CJTBlocksCouplingController->initCoupling, CJTBlocksCouplingController->getBlocks, CJTCouplingModel->getPinsBlocks, CJTPinsBlockSQLView->exec, CJTMYSQLQueueDriver->select

This issue is related only to Plus version (fixed here https://github.com/wipeoutmedia/css-javascript-toolbox-plus/issues/6 , but wasn't distributed yet).

Also you added three links:
https://wordpress.org/support/topic/all-kinds-of-database-errors
http://css-javascript-toolbox.com/support/topic/several-sites-where-cjt-will-not-load-or-is-showing-errors-in-the-log/
https://wordpress.org/support/topic/fatal-error-on-install-24

Two of them are related to exactly same (fixed) problem:
https://wordpress.org/support/topic/all-kinds-of-database-errors
http://css-javascript-toolbox.com/support/topic/several-sites-where-cjt-will-not-load-or-is-showing-errors-in-the-log/

While one of them is completely different:
https://wordpress.org/support/topic/fatal-error-on-install-24

Moreover it is related to two independent problems, so I have created separated issues for them
https://github.com/wipeoutmedia/css-javascript-toolbox/issues/7
https://github.com/wipeoutmedia/css-javascript-toolbox/issues/6

**Comment by lppdev** [comment]
I am having this issue as well:
`[04-Apr-2016 00:48:51 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') LEFT JOIN `wp_cjtoolbox_plus_block_pintype` pt ON blocks.`id` = pt.`blockId` W' at line 1 for query SELECT blocks.id,blocks.owner,blocks.name,blocks.pinPoint,blocks.location,blocks.links,blocks.expressions,0 as blocksGroup FROM wp_cjtoolbox_blocks blocks LEFT JOIN wp_cjtoolbox_block_pins pins0 ON blocks.id = pins0.blockId AND pins0.pin='categories' AND pins0.value IN(  ) LEFT JOIN `wp_cjtoolbox_plus_block_pintype` pt ON blocks.`id` = pt.`blockId` WHERE ( ( ( `backupId` IS NULL ) AND ( `state` = "active" ) ) AND ( ( pt.pinName = 'category' AND pt.invert = 1  ) ) AND ( (  ( pins0.pin IS NULL ) AND ( pins0.value IS NULL ) ) ) ); made by require('C:\HostingSpaces\admin\GritsGoBang.org\wwwroot\wordpress\wp-blog-header.php'), require_once('C:\HostingSpaces\admin\GritsGoBang.org\wwwroot\wordpress\wp-includes\template-loader.php'), do_action('template_redirect'), call_user_func_array, CJTBlocksCouplingController->initCoupling, CJTBlocksCouplingController->getBlocks, CJTCouplingModel->getPinsBlocks, apply_filters('cjt-blocks-coupling-model-blocks-queue'), call_user_func_array, CJTPlusHooksCJTBlockAssignmentNegative->_blocksQueue`

The result is a 500 error and a non-loading site - is there a solution?

**Comment by lppdev** [comment]
The undistributed fix above is no longer available:  https://github.com/wipeoutmedia/css-javascript-toolbox-plus/issues/6 

I have deactivated the Plus version (sadly) - hoping that will solve the problem until a Plus fix is available.  

It might be worth noting that once this error appears above all my WordPress sites hosted on that same server which utilize css-javascript-toolbox-plus are unable to load.  WordPres sites on the same server which do not use css-javascript-toolbox-plus load just fine during those times.  I'm guessing it is specific to the MySQL css-javascript-toolbox-plus db tables?

**Comment by xpointer** [comment]
I will get this issue fixed, I'm just checking the solution https://github.com/wipeoutmedia/css-javascript-toolbox-plus/commit/d62681d90601c8005bd82af993e918d8ebc3150a trying to understand 
We've this issue even before negative assignment feature were exists ! This is why I'm trying to understand how negative assignment causes this !

Date: Mon, 4 Apr 2016 02:29:07 -0700

**Comment by lppdev** [comment]
Thanks for the replies, this plugin should be considered an essential plugin for all WP site developers - let me know if I can help with debugging, testing
