### ISSUE TITLE
Installation management for PHP and MySQL compatibility

### ISSUE THREAD

**Issue by wipeoutmedia** [wipeoutmedia/css-javascript-toolbox#3]
A lot of users have emailed us when they have problems with installation.  I think we need to handle this better and allow CJT to check for things like PHP version, MySQL version, and even security plugins maybe. A part of me is a unhappy that we created an AJAX-based installation system.  Sometimes this falls over with some .htaccess ModSecurity rules within security plugins such as Bullet Proof Security.  Other times, a rogue plugin may hijack the installation process, or even utilise important resources that CJT relies on for proper operation. For example, users have responded to issues where they cannot create code blocks or their code blocks will not Save resulting in an endless loop.  Installation can also get stuck in an endless loop during the template installation step.

I have copied and pasted some related information that we've discussed - see below:
_____________________________________

Review errors handling / logging. For example, when I have installed your plugin on hosting with PHP 5.2 I have many error messages. It can make users very angry. Better to check PHP version before install and notice user about requirements ("ask support of your hosting to update PHP")
https://wordpress.org/support/topic/warning-and-fatal-error-12

AND

Review errors handling on install (like https://wordpress.org/support/topic/wont-install-17 ). Developers often forget to track AJAX / JS errors, so process silently dead. Even if some security plugin stopping installation from finishing - better to show error message about it.
https://wordpress.org/support/topic/wont-install-17

**Comment by ivanwebpro** [comment]
This problem 

> when I have installed your plugin on hosting with PHP 5.2 I have many error messages. It can make users very angry. Better to check PHP version before install and notice user about requirements ("ask support of your hosting to update PHP"), https://wordpress.org/support/topic/warning-and-fatal-error-12

was solved in https://github.com/wipeoutmedia/css-javascript-toolbox/issues/9

**Comment by ivanwebpro** [comment]
This problem:

> Review errors handling on install (like https://wordpress.org/support/topic/wont-install-17 ). Developers often forget to track AJAX / JS errors, so process silently dead. Even if some security plugin stopping installation from finishing - better to show error message about it.
https://wordpress.org/support/topic/wont-install-17 .

was solved too (in #13 and #14 ).

MySQL version don't have to be checked because I never saw errors directly related to MySQL version (syntax errors is different kind of errors).

So I close this general issue and more specific issues for installation problems will be used instead.
