### ISSUE TITLE
PHP version check on activation

### ISSUE THREAD

**Issue by ivanwebpro** [wipeoutmedia/css-javascript-toolbox#9]
When I have installed this plugin on hosting with PHP 5.2 I have many error messages. 

Better to check PHP version before install and notice user about requirements ("ask support of your hosting to update PHP").

Also this problem mentioned here https://wordpress.org/support/topic/warning-and-fatal-error-12

**Comment by ivanwebpro** [comment]
Fixed by the commit https://github.com/wipeoutmedia/css-javascript-toolbox/commit/120bed3d809d3e71cf6beb0572244dc6763c6a51

**Comment by wipeoutmedia** [comment]
Thanks Ivan
